name: Build xformers for Windows + CUDA 11.8

on:
  workflow_dispatch:  # 支持手动触发
    inputs:
      release_tag:
        description: 'Release tag to fetch the zip from'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: windows-2022
    env:
      CUDA_VERSION: "11.8"  # CUDA 版本
    steps:
    - name: Enable long paths
      run: |
        reg add HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1 /f

    - name: Checkout code without checking out submodules
      uses: actions/checkout@v3
      with:
        submodules: false

    - name: Initialize submodules
      run: |
        git submodule update --init --recursive --no-checkout
        git submodule update --recursive

    - name: Set Git long paths
      run: |
        git config --global core.longpaths true

    - name: Verify Git long paths
      run: |
        git config --get core.longpaths

    - name: Install Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install CUDA Toolkit 11.8
      run: |
        choco install cuda --version=11.8 -y
        setx PATH "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin;%PATH%"

    - name: Build xformers wheel
      run: |
        python setup.py bdist_wheel

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: xformers-windows-cu118
        path: dist/

  release:
    needs: build
    runs-on: windows-2022
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: xformers-windows-cu118

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ github.run_number }}"
        release_name: "Windows CUDA 11.8 Build - Python 3.10"
        draft: false
        prerelease: false

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: dist/
        asset_name: "xformers-0.0.28post3+cu118_cp310_cp310-win_amd64.whl"
        asset_content_type: application/zip
